version: "3"
services:
  project-management-bug-tracker:
    image: "project-management-bug-tracker:latest"
    restart: always
    network_mode: bridge
    env_file: .env
    ports:
      - "5060:5060"
